[2025-07-11T11:03:35.699+0200] {processor.py:161} INFO - Started process (PID=42274) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:03:35.699+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:03:35.700+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:03:35.700+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:03:35.702+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:03:35.701+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:03:35.702+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:03:35.702+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:03:35.702+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:03:35.709+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-07-11T11:04:26.009+0200] {processor.py:161} INFO - Started process (PID=42828) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:04:26.012+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:04:26.013+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:04:26.013+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:04:26.016+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:04:26.016+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:04:26.017+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:04:26.017+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:04:26.017+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:04:26.028+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-07-11T11:05:19.888+0200] {processor.py:161} INFO - Started process (PID=43419) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:05:19.891+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:05:19.892+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:05:19.891+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:05:19.895+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:05:19.894+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:05:19.896+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:05:19.895+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:05:19.896+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:05:19.905+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-07-11T11:06:03.518+0200] {processor.py:161} INFO - Started process (PID=43953) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:06:03.521+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:06:03.521+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:06:03.521+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:06:03.524+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:06:03.523+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:06:03.524+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:06:03.524+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:06:03.524+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:06:03.530+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-07-11T11:07:05.588+0200] {processor.py:161} INFO - Started process (PID=44887) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:07:05.590+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:07:05.591+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:07:05.591+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:07:05.593+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:07:05.593+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:07:05.593+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:07:05.593+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:07:05.594+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:07:05.602+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-07-11T11:07:56.622+0200] {processor.py:161} INFO - Started process (PID=45760) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:07:56.625+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:07:56.626+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:07:56.625+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:07:56.628+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:07:56.627+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:07:56.628+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:07:56.628+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:07:56.628+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:07:56.633+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-07-11T11:08:40.613+0200] {processor.py:161} INFO - Started process (PID=46229) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:08:40.615+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:08:40.616+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:08:40.616+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:08:40.620+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:08:40.619+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:08:40.620+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:08:40.620+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:08:40.621+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:08:40.631+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-07-11T11:09:39.402+0200] {processor.py:161} INFO - Started process (PID=46996) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:09:39.405+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:09:39.406+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:09:39.405+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:09:39.409+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:09:39.408+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:09:39.409+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:09:39.409+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:09:39.409+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:09:39.416+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-07-11T11:10:43.570+0200] {processor.py:161} INFO - Started process (PID=47844) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:10:43.573+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:10:43.574+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:10:43.573+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:10:43.578+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:10:43.577+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:10:43.578+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:10:43.578+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:10:43.579+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:10:43.590+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-07-11T11:11:28.546+0200] {processor.py:161} INFO - Started process (PID=48421) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:11:28.549+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:11:28.550+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:11:28.549+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:11:28.554+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:11:28.553+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:11:28.554+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:11:28.554+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:11:28.554+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:11:28.566+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-07-11T11:12:15.079+0200] {processor.py:161} INFO - Started process (PID=49842) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:12:15.082+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:12:15.083+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:12:15.082+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:12:15.087+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:12:15.086+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:12:15.087+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:12:15.087+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:12:15.088+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:12:15.098+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-07-11T11:12:59.366+0200] {processor.py:161} INFO - Started process (PID=50432) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:12:59.368+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:12:59.369+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:12:59.368+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:12:59.372+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:12:59.371+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:12:59.372+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:12:59.372+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:12:59.373+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:12:59.384+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-07-11T11:13:16.610+0200] {processor.py:161} INFO - Started process (PID=50641) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:13:16.612+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:13:16.614+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:13:16.613+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:13:16.617+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:13:16.617+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:13:16.618+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:13:16.617+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:13:16.618+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:13:16.629+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-07-11T11:13:43.648+0200] {processor.py:161} INFO - Started process (PID=51069) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:13:43.650+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:13:43.651+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:13:43.650+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:13:43.653+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:13:43.652+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:13:43.653+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:13:43.653+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:13:43.653+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:13:43.659+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-07-11T11:14:07.997+0200] {processor.py:161} INFO - Started process (PID=51367) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:14:08.000+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:14:08.001+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:14:08.001+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:14:08.005+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:14:08.004+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:14:08.005+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:14:08.005+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:14:08.005+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:14:08.012+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-07-11T11:14:47.349+0200] {processor.py:161} INFO - Started process (PID=51816) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:14:47.352+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:14:47.353+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:14:47.352+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:14:47.356+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:14:47.355+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:14:47.356+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:14:47.356+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:14:47.356+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:14:47.367+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-07-11T11:15:00.606+0200] {processor.py:161} INFO - Started process (PID=51969) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:15:00.609+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:15:00.611+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:15:00.610+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:15:00.614+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:15:00.613+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:15:00.614+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:15:00.614+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:15:00.614+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:15:00.625+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-07-11T11:15:45.156+0200] {processor.py:161} INFO - Started process (PID=52519) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:15:45.158+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:15:45.160+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:15:45.159+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:15:45.162+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:15:45.161+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:15:45.162+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:15:45.162+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:15:45.162+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:15:45.171+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-07-11T11:15:47.443+0200] {processor.py:161} INFO - Started process (PID=52550) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:15:47.444+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:15:47.444+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:15:47.444+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:15:47.446+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:15:47.445+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:15:47.446+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:15:47.446+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:15:47.446+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:15:47.451+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-07-11T11:16:47.349+0200] {processor.py:161} INFO - Started process (PID=53296) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:16:47.352+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:16:47.355+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:16:47.354+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:16:47.359+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:16:47.358+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:16:47.359+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:16:47.359+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:16:47.359+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:16:47.367+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-07-11T11:16:49.669+0200] {processor.py:161} INFO - Started process (PID=53323) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:16:49.670+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:16:49.670+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:16:49.670+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:16:49.672+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:16:49.671+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:16:49.672+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:16:49.672+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:16:49.672+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:16:49.679+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-07-11T11:18:08.548+0200] {processor.py:161} INFO - Started process (PID=54160) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:18:08.548+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:18:08.549+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:18:08.549+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:18:08.551+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:18:08.551+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:18:08.551+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:18:08.551+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:18:08.551+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:18:08.557+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2025-07-11T11:18:58.403+0200] {processor.py:161} INFO - Started process (PID=54676) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:18:58.405+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:18:58.407+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:18:58.407+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:18:58.410+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:18:58.410+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:18:58.411+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:18:58.411+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:18:58.411+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:18:58.423+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-07-11T11:19:49.537+0200] {processor.py:161} INFO - Started process (PID=55252) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:19:49.540+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:19:49.542+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:19:49.542+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:19:49.545+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:19:49.545+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:19:49.546+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:19:49.546+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:19:49.546+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:19:49.554+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2025-07-11T11:20:35.758+0200] {processor.py:161} INFO - Started process (PID=55717) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:20:35.761+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:20:35.762+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:20:35.762+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:20:35.766+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:20:35.765+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:20:35.766+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:20:35.766+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:20:35.766+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:20:35.776+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-07-11T11:21:41.569+0200] {processor.py:161} INFO - Started process (PID=56438) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:21:41.571+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:21:41.572+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:21:41.572+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:21:41.575+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:21:41.574+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:21:41.575+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:21:41.575+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:21:41.575+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:21:41.581+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-07-11T11:22:26.447+0200] {processor.py:161} INFO - Started process (PID=56883) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:22:26.449+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:22:26.451+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:22:26.451+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:22:26.454+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:22:26.454+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:22:26.455+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:22:26.455+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:22:26.455+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:22:26.465+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-07-11T11:23:10.813+0200] {processor.py:161} INFO - Started process (PID=57323) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:23:10.816+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:23:10.817+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:23:10.816+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:23:10.818+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:23:10.818+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:23:10.818+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:23:10.818+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:23:10.818+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:23:10.824+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-07-11T11:23:55.847+0200] {processor.py:161} INFO - Started process (PID=57783) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:23:55.850+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:23:55.852+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:23:55.852+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:23:55.856+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:23:55.855+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:23:55.856+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:23:55.856+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:23:55.856+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:23:55.865+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-07-11T11:24:43.425+0200] {processor.py:161} INFO - Started process (PID=58256) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:24:43.428+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:24:43.429+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:24:43.428+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:24:43.430+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:24:43.430+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:24:43.430+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:24:43.430+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:24:43.431+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:24:43.436+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2025-07-11T11:25:29.601+0200] {processor.py:161} INFO - Started process (PID=58823) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:25:29.604+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:25:29.605+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:25:29.605+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:25:29.608+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:25:29.607+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:25:29.608+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:25:29.608+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:25:29.608+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:25:29.617+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-07-11T11:26:14.622+0200] {processor.py:161} INFO - Started process (PID=59286) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:26:14.625+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:26:14.626+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:26:14.626+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:26:14.629+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:26:14.628+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:26:14.629+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:26:14.629+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:26:14.629+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:26:14.638+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-07-11T11:26:57.975+0200] {processor.py:161} INFO - Started process (PID=59771) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:26:57.978+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:26:57.980+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:26:57.980+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:26:57.984+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:26:57.983+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:26:57.984+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:26:57.984+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:26:57.984+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:26:57.995+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-07-11T11:27:44.976+0200] {processor.py:161} INFO - Started process (PID=60283) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:27:44.979+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:27:44.980+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:27:44.980+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:27:44.984+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:27:44.983+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:27:44.984+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:27:44.984+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:27:44.984+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:27:44.995+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-07-11T11:28:28.675+0200] {processor.py:161} INFO - Started process (PID=60735) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:28:28.678+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:28:28.680+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:28:28.679+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:28:28.683+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:28:28.682+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:28:28.684+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:28:28.684+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:28:28.684+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:28:28.696+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-07-11T11:29:14.828+0200] {processor.py:161} INFO - Started process (PID=61232) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:29:14.831+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:29:14.832+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:29:14.831+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:29:14.833+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:29:14.833+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:29:14.833+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:29:14.833+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:29:14.833+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:29:14.839+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2025-07-11T11:30:17.098+0200] {processor.py:161} INFO - Started process (PID=61889) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:30:17.101+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:30:17.103+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:30:17.103+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:30:17.106+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:30:17.106+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:30:17.107+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:30:17.107+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:30:17.107+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:30:17.118+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-07-11T11:31:18.735+0200] {processor.py:161} INFO - Started process (PID=62531) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:31:18.737+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:31:18.739+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:31:18.738+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:31:18.741+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:31:18.740+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:31:18.741+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:31:18.741+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:31:18.741+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:31:18.748+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-07-11T11:32:02.765+0200] {processor.py:161} INFO - Started process (PID=62967) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:32:02.768+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:32:02.770+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:32:02.770+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:32:02.774+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:32:02.773+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:32:02.774+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:32:02.774+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:32:02.774+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:32:02.785+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-07-11T11:33:05.677+0200] {processor.py:161} INFO - Started process (PID=63787) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:33:05.680+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:33:05.682+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:33:05.681+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:33:05.687+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:33:05.685+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:33:05.687+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:33:05.687+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:33:05.687+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:33:05.701+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-07-11T11:33:47.426+0200] {processor.py:161} INFO - Started process (PID=64205) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:33:47.429+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:33:47.431+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:33:47.431+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:33:47.435+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:33:47.434+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:33:47.435+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:33:47.435+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:33:47.435+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:33:47.445+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-07-11T11:34:34.311+0200] {processor.py:161} INFO - Started process (PID=64678) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:34:34.314+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:34:34.315+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:34:34.315+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:34:34.318+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:34:34.318+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:34:34.318+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:34:34.318+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:34:34.319+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:34:34.327+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-07-11T11:35:18.922+0200] {processor.py:161} INFO - Started process (PID=65118) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:35:18.925+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:35:18.927+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:35:18.927+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:35:18.931+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:35:18.930+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:35:18.931+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:35:18.931+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:35:18.931+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:35:18.943+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-07-11T11:36:18.505+0200] {processor.py:161} INFO - Started process (PID=65806) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:36:18.508+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:36:18.510+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:36:18.509+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:36:18.513+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:36:18.512+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:36:18.513+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:36:18.513+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:36:18.513+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:36:18.523+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-07-11T11:37:03.099+0200] {processor.py:161} INFO - Started process (PID=66283) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:37:03.102+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:37:03.104+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:37:03.104+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:37:03.107+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:37:03.106+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:37:03.107+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:37:03.107+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:37:03.108+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:37:03.114+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-07-11T11:37:46.087+0200] {processor.py:161} INFO - Started process (PID=66712) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:37:46.090+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:37:46.092+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:37:46.091+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:37:46.095+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:37:46.094+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:37:46.095+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:37:46.095+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:37:46.096+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:37:46.106+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-07-11T11:38:29.879+0200] {processor.py:161} INFO - Started process (PID=67156) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:38:29.882+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:38:29.884+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:38:29.883+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:38:29.887+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:38:29.886+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:38:29.887+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:38:29.887+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:38:29.887+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:38:29.896+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-07-11T11:39:15.422+0200] {processor.py:161} INFO - Started process (PID=67645) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:39:15.424+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:39:15.426+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:39:15.426+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:39:15.429+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:39:15.429+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:39:15.430+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:39:15.429+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:39:15.430+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:39:15.437+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-07-11T11:40:00.500+0200] {processor.py:161} INFO - Started process (PID=68160) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:40:00.503+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:40:00.505+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:40:00.505+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:40:00.509+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:40:00.508+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:40:00.510+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:40:00.509+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:40:00.510+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:40:00.519+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-07-11T11:40:44.857+0200] {processor.py:161} INFO - Started process (PID=68630) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:40:44.860+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:40:44.861+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:40:44.861+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:40:44.865+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:40:44.864+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:40:44.865+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:40:44.865+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:40:44.865+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:40:44.875+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-07-11T11:41:29.018+0200] {processor.py:161} INFO - Started process (PID=69058) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:41:29.021+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:41:29.024+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:41:29.023+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:41:29.028+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:41:29.027+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:41:29.028+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:41:29.028+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:41:29.029+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:41:29.040+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-07-11T11:42:11.725+0200] {processor.py:161} INFO - Started process (PID=69670) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:42:11.728+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:42:11.730+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:42:11.729+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:42:11.733+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:42:11.732+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:42:11.733+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:42:11.733+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:42:11.734+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:42:11.745+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-07-11T11:42:53.502+0200] {processor.py:161} INFO - Started process (PID=70123) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:42:53.504+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:42:53.507+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:42:53.506+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:42:53.510+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:42:53.509+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:42:53.510+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:42:53.510+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:42:53.510+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:42:53.521+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-07-11T11:43:57.598+0200] {processor.py:161} INFO - Started process (PID=70855) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:43:57.601+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:43:57.602+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:43:57.601+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:43:57.603+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:43:57.603+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:43:57.603+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:43:57.603+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:43:57.604+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:43:57.611+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-07-11T11:44:43.377+0200] {processor.py:161} INFO - Started process (PID=71427) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:44:43.378+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:44:43.380+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:44:43.380+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:44:43.383+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:44:43.383+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:44:43.384+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:44:43.384+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:44:43.384+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:44:43.394+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2025-07-11T11:45:30.533+0200] {processor.py:161} INFO - Started process (PID=71964) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:45:30.535+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:45:30.537+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:45:30.537+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:45:30.540+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:45:30.540+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:45:30.541+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:45:30.541+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:45:30.541+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:45:30.550+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-07-11T11:46:13.780+0200] {processor.py:161} INFO - Started process (PID=72461) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:46:13.783+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:46:13.785+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:46:13.784+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:46:13.788+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:46:13.787+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:46:13.788+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:46:13.788+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:46:13.788+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:46:13.796+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2025-07-11T11:47:15.502+0200] {processor.py:161} INFO - Started process (PID=73085) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:47:15.505+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:47:15.507+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:47:15.507+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:47:15.510+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:47:15.509+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:47:15.510+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:47:15.510+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:47:15.511+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:47:15.519+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-07-11T11:48:18.605+0200] {processor.py:161} INFO - Started process (PID=73774) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:48:18.608+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:48:18.609+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:48:18.609+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:48:18.612+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:48:18.612+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:48:18.613+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:48:18.613+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:48:18.613+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:48:18.622+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-07-11T11:49:01.339+0200] {processor.py:161} INFO - Started process (PID=74184) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:49:01.342+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:49:01.344+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:49:01.343+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:49:01.347+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:49:01.346+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:49:01.347+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:49:01.347+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:49:01.347+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:49:01.357+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2025-07-11T11:50:06.307+0200] {processor.py:161} INFO - Started process (PID=74822) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:50:06.310+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:50:06.312+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:50:06.312+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:50:06.316+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:50:06.315+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:50:06.316+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:50:06.316+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:50:06.316+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:50:06.324+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-07-11T11:50:52.052+0200] {processor.py:161} INFO - Started process (PID=75306) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:50:52.053+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:50:52.054+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:50:52.054+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:50:52.056+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:50:52.056+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:50:52.057+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:50:52.057+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:50:52.057+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:50:52.066+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-07-11T11:51:37.142+0200] {processor.py:161} INFO - Started process (PID=75751) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:51:37.145+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:51:37.147+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:51:37.146+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:51:37.150+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:51:37.149+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:51:37.150+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:51:37.150+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:51:37.151+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:51:37.164+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-07-11T11:52:41.663+0200] {processor.py:161} INFO - Started process (PID=76417) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:52:41.666+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:52:41.668+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:52:41.667+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:52:41.671+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:52:41.670+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:52:41.671+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:52:41.671+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:52:41.672+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:52:41.682+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-07-11T11:53:45.086+0200] {processor.py:161} INFO - Started process (PID=77053) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:53:45.089+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:53:45.091+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:53:45.090+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:53:45.094+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:53:45.094+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:53:45.094+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:53:45.094+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:53:45.095+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:53:45.103+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-07-11T11:54:29.702+0200] {processor.py:161} INFO - Started process (PID=77478) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:54:29.705+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:54:29.707+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:54:29.707+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:54:29.710+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:54:29.710+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:54:29.711+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:54:29.711+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:54:29.711+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:54:29.722+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-07-11T11:55:16.221+0200] {processor.py:161} INFO - Started process (PID=77954) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:55:16.224+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:55:16.226+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:55:16.225+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:55:16.229+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:55:16.228+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:55:16.229+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:55:16.229+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:55:16.229+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:55:16.238+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-07-11T11:56:17.019+0200] {processor.py:161} INFO - Started process (PID=78635) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:56:17.022+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:56:17.024+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:56:17.024+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:56:17.028+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:56:17.027+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:56:17.028+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:56:17.028+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:56:17.028+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:56:17.039+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-07-11T11:56:59.346+0200] {processor.py:161} INFO - Started process (PID=79058) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:56:59.349+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:56:59.351+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:56:59.351+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:56:59.354+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:56:59.354+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:56:59.355+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:56:59.355+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:56:59.355+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:56:59.369+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-07-11T11:58:05.201+0200] {processor.py:161} INFO - Started process (PID=79704) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:58:05.203+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:58:05.205+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:58:05.204+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:58:05.209+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:58:05.208+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:58:05.209+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:58:05.209+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:58:05.209+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:58:05.222+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-07-11T11:58:49.895+0200] {processor.py:161} INFO - Started process (PID=80146) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:58:49.898+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:58:49.899+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:58:49.899+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:58:49.903+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:58:49.902+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:58:49.903+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:58:49.903+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:58:49.903+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:58:49.914+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-07-11T11:59:56.872+0200] {processor.py:161} INFO - Started process (PID=80823) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:59:56.875+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T11:59:56.876+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:59:56.876+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:59:56.880+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:59:56.879+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T11:59:56.880+0200] {logging_mixin.py:188} INFO - [2025-07-11T11:59:56.880+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T11:59:56.880+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T11:59:56.893+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-07-11T12:00:44.598+0200] {processor.py:161} INFO - Started process (PID=81320) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T12:00:44.601+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T12:00:44.603+0200] {logging_mixin.py:188} INFO - [2025-07-11T12:00:44.603+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T12:00:44.606+0200] {logging_mixin.py:188} INFO - [2025-07-11T12:00:44.606+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T12:00:44.607+0200] {logging_mixin.py:188} INFO - [2025-07-11T12:00:44.607+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T12:00:44.607+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T12:00:44.618+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-07-11T12:01:30.713+0200] {processor.py:161} INFO - Started process (PID=81795) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T12:01:30.716+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T12:01:30.717+0200] {logging_mixin.py:188} INFO - [2025-07-11T12:01:30.717+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T12:01:30.720+0200] {logging_mixin.py:188} INFO - [2025-07-11T12:01:30.719+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T12:01:30.720+0200] {logging_mixin.py:188} INFO - [2025-07-11T12:01:30.720+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T12:01:30.720+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T12:01:30.728+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2025-07-11T12:02:29.630+0200] {processor.py:161} INFO - Started process (PID=82368) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T12:02:29.633+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T12:02:29.635+0200] {logging_mixin.py:188} INFO - [2025-07-11T12:02:29.634+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T12:02:29.638+0200] {logging_mixin.py:188} INFO - [2025-07-11T12:02:29.638+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T12:02:29.639+0200] {logging_mixin.py:188} INFO - [2025-07-11T12:02:29.638+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T12:02:29.639+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T12:02:29.650+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-07-11T12:03:35.187+0200] {processor.py:161} INFO - Started process (PID=83045) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T12:03:35.188+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T12:03:35.189+0200] {logging_mixin.py:188} INFO - [2025-07-11T12:03:35.189+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T12:03:35.192+0200] {logging_mixin.py:188} INFO - [2025-07-11T12:03:35.191+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T12:03:35.192+0200] {logging_mixin.py:188} INFO - [2025-07-11T12:03:35.192+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T12:03:35.192+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T12:03:35.200+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-07-11T12:04:19.668+0200] {processor.py:161} INFO - Started process (PID=83463) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T12:04:19.671+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T12:04:19.672+0200] {logging_mixin.py:188} INFO - [2025-07-11T12:04:19.672+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T12:04:19.677+0200] {logging_mixin.py:188} INFO - [2025-07-11T12:04:19.676+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T12:04:19.677+0200] {logging_mixin.py:188} INFO - [2025-07-11T12:04:19.677+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T12:04:19.677+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T12:04:19.686+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-07-11T12:05:05.317+0200] {processor.py:161} INFO - Started process (PID=83965) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T12:05:05.318+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-07-11T12:05:05.320+0200] {logging_mixin.py:188} INFO - [2025-07-11T12:05:05.319+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T12:05:05.323+0200] {logging_mixin.py:188} INFO - [2025-07-11T12:05:05.322+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-07-11T12:05:05.323+0200] {logging_mixin.py:188} INFO - [2025-07-11T12:05:05.323+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-07-11T12:05:05.323+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-07-11T12:05:05.333+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
